server:
  port: ${SERVER_PORT:8185}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:payments}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DEFAULT_SCHEMA:payments}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:loan_management}
    password: ${DATABASE_PASSWORD:password}
    username: ${DATABASE_USER:default}
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
  api-docs:
    path: ${API_DOCS_PATH:/v3/api-docs}
logging:
  level:
    root: warn
    com.dcat23.loanmgmt: debug